from selenium import webdriver
driver = webdriver.Chrome(executable_path="C:\Program Files\Google\Chrome\Application\chromedriver.exe")
driver.maximize_window()
driver.get("file:///H:/project/demo.html")
driver.find_element_by_id('name').send_keys('pirai infotech')
driver.find_element_by_id('register').send_keys('028767')
driver.find_element_by_id('email').send_keys('hr@piraiinfo.com')
driver.find_element_by_id('phone').send_keys('9894233995')
driver.find_element_by_id('sex').send_keys('male')
driver.find_element_by_id('country').send_keys('india')
driver.find_element_by_id('addrow').click()
